// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool({
  name: "list_properties",
  title: "Immobilien auflisten",
  description: "Listet alle Immobilien des angemeldeten Vermieters mit Adresse, Baujahr und Kaufpreis.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client(ctx).from("properties").select("id,name,street,zip,city,build_year,purchase_price,purchase_date").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tenants.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tenants_default = defineTool2({
  name: "list_tenants",
  title: "Mieter auflisten",
  description: "Listet Mieter des angemeldeten Vermieters. Optional nach Objekt-ID gefiltert.",
  inputSchema: {
    property_id: z.string().uuid().optional().describe("Optional: nur Mieter dieses Objekts")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client2(ctx).from("tenants").select("id,full_name,email,phone,lease_start,lease_end,deposit,property_id").order("full_name");
    if (property_id) q = q.eq("property_id", property_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tenants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_payments_default = defineTool3({
  name: "list_payments",
  title: "Zahlungen auflisten",
  description: "Listet die letzten Zahlungen (Mieteing\xE4nge, NK-Vorauszahlungen) des Vermieters.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Maximale Anzahl (Standard 50)"),
    since: z2.string().optional().describe("Nur Zahlungen ab diesem Datum (YYYY-MM-DD)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, since }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client3(ctx).from("payments").select("id,paid_on,kind,amount,note,tenant_id,property_id").order("paid_on", { ascending: false }).limit(limit ?? 50);
    if (since) q = q.gte("paid_on", since);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { payments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-expense.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_expense_default = defineTool4({
  name: "create_expense",
  title: "Ausgabe erfassen",
  description: "Erfasst eine neue Ausgabe (Handwerker, Versicherung, Zinsen etc.) f\xFCr ein Objekt.",
  inputSchema: {
    property_id: z3.string().uuid().describe("Objekt-ID (aus list_properties)"),
    spent_on: z3.string().describe("Datum YYYY-MM-DD"),
    amount: z3.number().positive().describe("Betrag in Euro"),
    description: z3.string().min(1).describe("Kurzbeschreibung"),
    vendor: z3.string().optional().describe("Rechnungssteller"),
    category: z3.enum(["immediate", "depreciable", "financing", "utilities_passthrough", "other"]).optional().describe("Steuerkategorie")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client4(ctx).from("expenses").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Ausgabe erfasst: ${data.id}` }],
      structuredContent: { expense: data }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool5({
  name: "list_tasks",
  title: "Aufgaben auflisten",
  description: "Listet offene Aufgaben des Vermieters (Fristen, TODOs).",
  inputSchema: {
    include_done: z4.boolean().optional().describe("Auch erledigte Aufgaben anzeigen")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_done }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client5(ctx).from("tasks").select("*").order("due_date", { ascending: true, nullsFirst: false });
    if (!include_done) q = q.neq("status", "done");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ikgwsdviewtvaitlpijg";
var mcp_default = defineMcp({
  name: "immoniq-mcp",
  title: "ImmonIQ",
  version: "0.1.0",
  instructions: "Tools f\xFCr ImmonIQ, das digitale Vermieter-Cockpit. Lies Immobilien, Mieter, Zahlungen und Aufgaben oder erfasse Ausgaben im Namen des angemeldeten Nutzers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_properties_default, list_tenants_default, list_payments_default, create_expense_default, list_tasks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
